  name: dbs
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - pandas
  - geopandas
  - descartes
  - pygeos
  - pyarrow>=2.0.0

  # dev dependencies
  - poetry
  - jupytext
  - ipykernel